project:
  type: website
  output-dir: docs

website:
  title: "Kevin Miller"
  navbar:
    right:
      - about.qmd
      - index.qmd
      - icon: github
        href: https://github.com/kmiller999
      - icon: linkedin
        href: https://www.linkedin.com/in/kevin-miller-375031204/
      - icon: envelope
        href: mailto:kevinmiller1218@gmail.com
format:
  html:
    theme: darkly
    css: styles.css



