project:
  type: website
  output-dir: docs

website:
  title: "Kevin Miller"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
    right:
      - icon: envelope
        href: mailto:kevinmiller1218@gmail.com
      - icon: github
        href: https://github.com/kmiller999
      - icon: linkedin
        href: https://www.linkedin.com/in/kevin-miller-msda/

format:
  html:
    theme: darkly
    css: styles.css


